"""Tests for QualityAssuranceAgent."""

import json
from unittest.mock import patch

import pytest

from agents.quality_assurance import QualityAssuranceAgent


@pytest.fixture
def mock_config():
    """Mock configuration for testing."""
    return {
        "scheduling": {"opencode_url": "http://localhost:4096", "auto_commit": False},
        "general": {"journal_directory": "/tmp/test-journal"},
        "quality": {"min_commits_for_section": 3},
        "opencode": {"model": "test-model", "provider": "test-provider"},
    }


@pytest.fixture
def quality_assurance_agent():
    """Create a QualityAssuranceAgent instance with mocked dependencies."""
    config = {
        "scheduling": {"opencode_url": "http://localhost:4096", "auto_commit": False},
        "general": {"journal_directory": "/tmp/test-journal"},
        "quality": {"min_commits_for_section": 3},
        "opencode": {"model": "test-model", "provider": "test-provider"},
    }
    with patch("agents.quality_assurance.get_config") as mock_get_config:
        mock_get_config.return_value = config
        with patch("agents.quality_assurance.OpenCodeClient") as mock_opencode_client:
            agent = QualityAssuranceAgent()
            mock_opencode_client.assert_called_once_with(base_url="http://localhost:4096")
            yield agent


@pytest.fixture
def sample_content():
    """Sample journal content for testing."""
    return """# December 31, 2025

**Work Summary:** ~8.0 hours, ~1400 lines - Auto-generated by journal automation

## Summary
Focused on comic-pile improvements.

## Repositories Worked On
- `~/code/comic-pile` (43 commits)

- **Total: 43 commits**

## comic-pile
**Staleness Awareness**
- feat: Add Staleness Awareness UI

---
## Projects Legend

### comic-pile
Test project description."""


@pytest.fixture
def sample_git_data():
    """Sample git data for testing."""
    return {
        "date": "2025-12-31",
        "is_work_day": True,
        "total_commits": 43,
        "total_loc_added": 1200,
        "total_loc_deleted": 200,
        "estimated_hours": 8.0,
        "repos": {
            "comic-pile": {
                "commits": 43,
                "commits_by_category": {"feat": 25, "fix": 10, "refactor": 5, "docs": 3},
                "top_features": ["feat(TASK-102): Add Staleness Awareness UI"],
            }
        },
    }


class TestQualityAssuranceAgent:
    """Test suite for QualityAssuranceAgent."""

    @patch("agents.quality_assurance.get_config")
    @patch("agents.quality_assurance.OpenCodeClient")
    def test_init(self, mock_opencode, mock_get_config):
        """Test QualityAssuranceAgent initialization."""
        mock_get_config.return_value = {"scheduling": {"opencode_url": "http://localhost:4096"}}

        QualityAssuranceAgent()

        mock_opencode.assert_called_once_with(base_url="http://localhost:4096")

    @patch("agents.quality_assurance.validate_markdown_syntax")
    def test_validate_and_commit_pass(
        self,
        mock_validate,
        quality_assurance_agent,
        sample_content,
        sample_git_data,
        temp_dir,
    ):
        """Test validate_and_commit with passing content."""
        quality_assurance_agent.config["general"]["journal_directory"] = str(temp_dir)
        quality_assurance_agent.config["scheduling"]["auto_commit"] = False

        mock_validate.return_value = []

        quality_assurance_agent.client.chat.return_value = {
            "content": json.dumps(
                {
                    "score": 85,
                    "reasoning": "Good content",
                    "suggestions": ["Improve X"],
                    "strengths": ["Good Y"],
                }
            )
        }

        result = quality_assurance_agent.validate_and_commit(
            sample_content, sample_git_data, "2025-12-31"
        )

        assert result["status"] == "pass"
        assert result["overall_score"] == 85
        assert result["file_path"] != ""
        assert result["committed"] is False
        assert "Good content" in result["reasoning"]

    @patch("agents.quality_assurance.validate_markdown_syntax")
    def test_validate_and_commit_fail_low_score(
        self,
        mock_validate,
        quality_assurance_agent,
        sample_content,
        sample_git_data,
    ):
        """Test validate_and_commit fails with low quality score."""
        mock_validate.return_value = []

        quality_assurance_agent.client.chat.return_value = {
            "content": json.dumps(
                {"score": 50, "reasoning": "Poor quality", "suggestions": [], "strengths": []}
            )
        }

        result = quality_assurance_agent.validate_and_commit(
            sample_content, sample_git_data, "2025-12-31"
        )

        assert result["status"] == "fail"
        assert result["overall_score"] == 50
        assert result["file_path"] == ""
        assert result["committed"] is False

    @patch("agents.quality_assurance.validate_markdown_syntax")
    def test_validate_and_commit_critical_issue(
        self,
        mock_validate,
        quality_assurance_agent,
        sample_content,
        sample_git_data,
    ):
        """Test validate_and_commit fails with critical issue."""
        mock_validate.return_value = ["CRITICAL: malformed syntax"]

        quality_assurance_agent.client.chat.return_value = {
            "content": json.dumps(
                {
                    "score": 80,
                    "reasoning": "Good content",
                    "suggestions": [],
                    "strengths": [],
                }
            )
        }

        result = quality_assurance_agent.validate_and_commit(
            sample_content, sample_git_data, "2025-12-31"
        )

        assert result["status"] == "fail"

    @patch("utils.git_utils.stage_and_commit")
    @patch("agents.quality_assurance.validate_markdown_syntax")
    def test_validate_and_commit_with_auto_commit(
        self,
        mock_validate,
        mock_stage_commit,
        quality_assurance_agent,
        sample_content,
        sample_git_data,
        temp_dir,
    ):
        """Test validate_and_commit with auto_commit enabled."""
        quality_assurance_agent.config["general"]["journal_directory"] = str(temp_dir)
        quality_assurance_agent.config["scheduling"]["auto_commit"] = True

        mock_validate.return_value = []
        mock_stage_commit.return_value = True

        quality_assurance_agent.client.chat.return_value = {
            "content": json.dumps(
                {
                    "score": 85,
                    "reasoning": "Good content",
                    "suggestions": [],
                    "strengths": [],
                }
            )
        }

        result = quality_assurance_agent.validate_and_commit(
            sample_content, sample_git_data, "2025-12-31"
        )

        assert result["status"] == "pass"
        assert result["committed"] is True
        mock_stage_commit.assert_called_once()

    @patch("agents.quality_assurance.validate_markdown_syntax")
    def test_validate_and_commit_syntax_errors(
        self,
        mock_validate,
        quality_assurance_agent,
        sample_content,
        sample_git_data,
    ):
        """Test validate_and_commit with syntax errors."""
        mock_validate.return_value = ["Unclosed code block"]

        quality_assurance_agent.client.chat.return_value = {
            "content": json.dumps(
                {"score": 75, "reasoning": "Good", "suggestions": [], "strengths": []}
            )
        }

        result = quality_assurance_agent.validate_and_commit(
            sample_content, sample_git_data, "2025-12-31"
        )

        assert result["status"] == "pass"
        assert len(result["issues"]) > 0
        assert "Unclosed code block" in result["issues"][0]

    def test_review_quality(self, quality_assurance_agent, sample_content):
        """Test _review_quality."""
        quality_assurance_agent.client.chat.return_value = {
            "content": json.dumps(
                {
                    "score": 85,
                    "reasoning": "Well written",
                    "suggestions": ["Add more detail"],
                    "strengths": ["Clear structure"],
                }
            )
        }

        git_data = {"total_commits": 10, "repos": {"test": {}}, "is_work_day": True}

        result = quality_assurance_agent._review_quality(sample_content, git_data, "2025-12-31")

        assert result["score"] == 85
        assert result["reasoning"] == "Well written"
        assert "Add more detail" in result["suggestions"]
        assert "Clear structure" in result["strengths"]

    def test_review_quality_json_error(self, quality_assurance_agent, sample_content):
        """Test _review_quality handles JSON errors gracefully."""
        quality_assurance_agent.client.chat.return_value = {"content": "invalid json"}

        git_data = {"total_commits": 10, "repos": {"test": {}}, "is_work_day": True}

        result = quality_assurance_agent._review_quality(sample_content, git_data, "2025-12-31")

        assert result["score"] == 70
        assert "default score" in result["reasoning"]

    @patch("agents.quality_assurance.get_config")
    def test_check_cross_references_valid(
        self, mock_get_config, quality_assurance_agent, sample_content
    ):
        """Test _check_cross_references with valid content."""
        mock_get_config.return_value = {"quality": {"min_commits_for_section": 3}}

        git_data = {"repos": {"comic-pile": {"commits": 5}}}

        result = quality_assurance_agent._check_cross_references(sample_content, git_data)

        assert len(result) == 0

    def test_check_cross_references_missing_repo(self, quality_assurance_agent):
        """Test _check_cross_references detects missing repo."""
        git_data = {"repos": {"missing-repo": {"commits": 5}}}

        result = quality_assurance_agent._check_cross_references("Test content", git_data)

        assert len(result) > 0
        assert "Missing reference" in result[0]
        assert "missing-repo" in result[0]

    def test_check_cross_references_legend_mismatch(self, quality_assurance_agent):
        """Test _check_cross_references detects legend mismatch."""
        git_data = {"repos": {"comic-pile": {"commits": 5}}}

        content = "comic-pile is mentioned here\n### unknown-repo\nDescription"

        result = quality_assurance_agent._check_cross_references(content, git_data)

        assert len(result) > 0
        assert "not in git data" in result[0]

    def test_create_journal_file(self, quality_assurance_agent, temp_dir):
        """Test _create_journal_file."""
        quality_assurance_agent.config["general"]["journal_directory"] = str(temp_dir)

        content = "# Test Content"
        date = "2025-12-31"

        result = quality_assurance_agent._create_journal_file(content, date)

        assert "2025/12/31.md" in result

        file_path = temp_dir / result
        assert file_path.exists()

        with open(file_path) as f:
            assert f.read() == content

    @patch("agents.quality_assurance.get_config")
    def test_create_journal_file_invalid_date(
        self, mock_get_config, quality_assurance_agent, temp_dir
    ):
        """Test _create_journal_file with invalid date."""
        mock_get_config.return_value = {"general": {"journal_directory": str(temp_dir)}}

        content = "# Test"
        date = "invalid-date"

        with pytest.raises(ValueError):
            quality_assurance_agent._create_journal_file(content, date)

    @patch("utils.git_utils.stage_and_commit")
    def test_commit_file(self, mock_stage_commit, quality_assurance_agent, temp_dir):
        """Test _commit_file."""
        mock_stage_commit.return_value = True

        result = quality_assurance_agent._commit_file("2025/12/31.md", "2025-12-31")

        assert result is True
        mock_stage_commit.assert_called_once()

    @patch("utils.git_utils.stage_and_commit")
    def test_commit_file_failure(self, mock_stage_commit, quality_assurance_agent, temp_dir):
        """Test _commit_file handles failure."""
        mock_stage_commit.return_value = False

        result = quality_assurance_agent._commit_file("2025/12/31.md", "2025-12-31")

        assert result is False
