#!/usr/bin/env python3
"""Markdown utility functions for journal automation."""

import re


def validate_markdown_syntax(content: str) -> list[str]:
    """Basic Markdown syntax validation."""
    errors = []

    # Check for unclosed code blocks
    code_blocks = content.count("```")
    if code_blocks % 2 != 0:
        errors.append("Unclosed code block detected")

    # Check for unclosed inline code
    inline_code = content.count("`")
    if inline_code % 2 != 0:
        errors.append("Unclosed inline code detected")

    # Check for unmatched headers (basic check - a full parser would be better)
    re.findall(r"^(#{1,6})\s", content, re.MULTILINE)

    return errors


def extract_commits_from_markdown(content: str, repo_name: str) -> int:
    """Count commits mentioned for a repo in markdown content."""
    # Look for commit counts in markdown
    pattern = rf"{re.escape(repo_name)}\s*\(\s*(\d+)\s*commits"
    matches = re.findall(pattern, content, re.IGNORECASE)
    return int(matches[0]) if matches else 0


def has_section(content: str, section_name: str) -> bool:
    """Check if markdown has a specific section."""
    pattern = rf"^##\s+{re.escape(section_name)}\s*$"
    return bool(re.search(pattern, content, re.MULTILINE))


def is_valid_filename(filename: str) -> bool:
    """Validate markdown filename follows YYYY/MM/DD.md format."""
    pattern = r"^\d{4}/\d{2}/\d{2}\.md$"
    return bool(re.match(pattern, filename))


def format_header(date: str, hours: float, loc: int) -> str:
    """Format journal entry header."""
    loc_str = f"~{loc:,} lines" if loc >= 1000 else f"~{loc} lines"
    hours_str = f"{hours:.1f} hours" if hours >= 1 else f"{int(hours * 60)} minutes"

    return f"""# {format_date(date)} ({date})

**Work Summary:** ~{hours_str}, {loc_str} - Auto-generated by journal automation"""


def format_date(date_str: str) -> str:
    """Convert YYYY-MM-DD to Month Day, Year format."""
    try:
        from datetime import datetime

        dt = datetime.strptime(date_str, "%Y-%m-%d")
        return dt.strftime("%B %d, %Y")
    except ValueError:
        return date_str
